
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

springdoc:
  api-docs:
    enabled: true
    path: '/docs'
  swagger-ui:
    path: '/docs-ui-user'
management:
  endpoints:
    web:
      exposure:
        include: "*"
